server:
  port: 8084

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml

spring:
  application:
    name: msa-service-coffee-status
  h2:
    console:
      enabled: true
      path: /h2console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/./msa-book/msa-service-coffee-status
    username: sa
    password: '1234'

  #Config Server
  cloud:
    config:
      uri: http://localhost:8888
      name: msa-architecture-config-server
      enabled: false

#Eureka Client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/
    enabled: true
    instance:
      preferIpAddress: true
      instance-id: