server:
  port: 8888

spring:
  application:
    name: msa-architecture-server-config

#config server:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/EUM-kmu/EUM-assignment.git
#          uri: file://D:\msa-architecture-server-config-git-repository

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/
    enabled: true