server:
  port: 9091

spring:
  application:
    name: msa-architecture-server-eureka

eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/, http://localhost:9092/eureka/