server:
  port: 8081

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml

spring:
  application:
    name: msa-service-coffee-member
  h2:
    console:
      enabled: true
      path: /h2console
  datasource:
    driver-class-name: org.h2.Driver
    url:  jdbc:h2:tcp://localhost/./msa-book/msa-service-coffee-member
    username: sa
    password:
  cloud:
    config:
      uri: http://localhost:8888
      name: msa-architecture-config-server
      enabled: false

#Eureka Client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/
    enabled: true
  instance:
    preferIpAddress: true
    instance-id: