server:
  port: 8083

spring:
  application:
    name: msa-service-coffee-order
  h2:
    console:
      enabled: true
      path: /h2console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/./msa-book/msa-service-coffee-order
    username: sa
    password:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create #OrderEntityJPO 테이블 자동 생성
  cloud:
    config:
      uri: http://localhost:8888
      name: msa-architecture-config-server
      enabled: false

#Eureka Client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/
    enabled: true
  instance:
    preferIpAddress: true
    instance-id: